homepage:
  ping: true
  version: true
  containers: true

portainer:
  ping: true
  version: true
  info: true
  containers: true
  images: true
  networks: true
  exec: true
  services: true
  tasks: true
  volumes: true
  system: true
  post: true
  allow_start: true
  allow_stop: true
  allow_restart: true
